---
version: "2.1"
services:
  smokeping:
    image: lscr.io/linuxserver/smokeping:latest
    container_name: aonog2022-smokeping
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Luanda
    volumes:
      - ./config/Targets:/config/Targets
      - ./config/General:/config/General
      - ./config/Probes:/config/Probes
      - ./config/data:/config/data
      - ./config/Alerts:/config/Alerts
      - ./config/scripts:/config/scripts
      - ./config/data/smokeping:/var/log/smokeping
      - ./config/sysctl.conf:/etc/sysctl.conf
      
    ports:
      - 80:80
    restart: unless-stopped
